name: Build Docker Image
on:
  pull_request_target:
    branches:
      - master
    types: 
      - opened
      - ready_for_review
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gcr.io/hoprassociation/hopr-admin:latest



