---
name: Release version

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'   # v1.0.0

concurrency:
  group: admin-release
  cancel-in-progress: true

jobs:
  build:
    name: docker-build
    runs-on: self-hosted-hoprnet-small
    steps:
      - name: Checkout hoprnet repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud Credentials
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

      - name: Login Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: scripts/NodeAdmin.Dockerfile
          tags: europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/hopr-admin:${{ github.ref_name }}
